#Should the mod be chosen by vote or randomly? (By vote = true, Random = false)
vote-start: true
#Do you want the game to start automatically when a certain number is reached?
player-start: true
#Should the game automatically start when reaching how many players?
player-start-count: 10
#Countdown to the start of the game after reaching the number of players. (Seconds)
player-start-time: 10
#How many seconds countdown when you type start game command. We recommend at least 2 seconds
start-countdown: 3
#It sets when lava will rise in Classic mode.(Applies to Trident, Elytra and Classic mode)
classic-start-time: 600
#It sets when lava will rise in Op mode.(Applies to TridentOp, ElytraOP and Op mode)
op-start-time: 60
#It sets the world size. (Default= 112)
world-size: 112
#World name where features will be applied
world-name: "world"
#It writes when PvP will be enabled.
pvp-allow: 90
#It writes how often the lava will rise, in seconds.
lava-delay: 3
#It writes at which layer the lava will start to rise. (1.8+ = 1, 1.18+ = -64)
lava-start-block: 1
#If you turn off AutoPickUp, the blocks you break will fall to the ground.
autopickup: true
#If you turn off AutoMelt, the crushed ore will come back as ore.
automelt: true
#If you deactivate it, the water won't turn to ice
water-to-ice:
    enabled: false #Not recommended if you do not have a powerful server
    low-y: 40
    high-y: 63
#If it is false the spectators can generate chunks
spectators-generate-chunks: true
#If it is true the water with lava does not turn to obsidian
#(But but when pvp opens, players can turn it into obsidian.)
obsidian-fix: true

#For example, people don't get themselves killed by putting a door. When the lava reaches a certain layer, it will check and if a person is below this layer, it will kill them.
#Which layer should it check underneath?
#It writes at which layer the lava will stop. (1.8+ = 256, 1.18+ = 320)
lava-border: 256
#Kills a player standing on a certain layer of lava. (border-kill has to be lower than lava-border!!!)
border-kill: 253

team:
  max-size: 2

# Sound settings for various game events
sound:
  countdown-sound: BLOCK_NOTE_BLOCK_PLING
  skip-sound: BLOCK_NOTE_BLOCK_PLING
  freeze-sound: BLOCK_NOTE_BLOCK_PLING
  start-sound: ENTITY_GENERIC_EXPLODE
  lava-rise-sound: BLOCK_NOTE_BLOCK_PLING
  winner-sound: ENTITY_FIREWORK_ROCKET_TWINKLE
  pvp-sound: BLOCK_NOTE_BLOCK_PLING
  shrink-sound: BLOCK_NOTE_BLOCK_PLING

# Custom death message settings
custom-death-messages:
  enabled: true
  havent-killer: "&c☠ &a%player%"
  have-killer: "&c⚔ &a%player% &cfrom &a%killer%"

# Reward system settings
rewards:
  enabled: true
  kill-player:
    - "eco give %player% 5"
  win-player:
    - "eco give %player% 3"
  death-player:
    - "eco give %player% -3"

# Vote multipliers based on player group(LuckPerms)
vote_multipliers:
  default: 1
  vip: 2

