name: KteRising
version: '2.1.2'
main: com.kteproject.kterising.KteRising
api-version: '1.20'
authors: [ KteProject ]
description: LavaRising Plugin
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
commands:
  kterising:
    description: "KteRising is the best!"