name: KteRising
version: 1.6.5
main: com.kterising.KteRising
api-version: '1.16'
author: Ruby, Ben Lordlex, Kaan Flod
softdepend: [PlaceholderAPI, LuckPerms]
commands:
  kterising:
    description: "KteRising Command"
