name: KteRising
version: 1.5
main: com.kterising.KteRising
api-version: '1.16'
author: Ruby, Ben Lordlex, Kaan Flod
depend: [PlaceholderAPI]
commands:
  kterising:
    description: "KteRising Command"
